### PR TITLE
Bug: Login Session issue in Mobile View

### LINKED ISSUE #54: [Bug]: Login Session Issue in Mobile View
### Detailed Description

I found this error in this project where I have logged in to the website but if i switch to mobile view it shows the login option again but going back to desktop view it shows i am logged in again... (Not everyone might encounter this but still looks like an error)

### Expected Behavior

I expected that it will be logged in even if i switch the screen size

### How can someone reproduce the behavior?

1. Go to the website on desktop view and login with your cred after this you would be able to see the account on navbar.
image
2. Do right click then inspect and reduce screen size so you can see the hamburger icon. 
3. Now click on icon. You will see the option to login again.
image
4. Finally if you go back to desktop view again, you will see that you are already logged in.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

This is looks amazing and helpful. Shout out to the whole team for this awesome project. 😄

### PR DESCRIPTION
**Pull request by AbhinavMV**
#### Description of the change\*
Fixed session issue in Mobile view
Added Profile and Logout button in mobile view.

image

CLOSES #ISSUENO 
Closes #54 
#### Checklist\*

**Please make sure you have done the following:**

- [x] 😄 I've read [CONTRIBUTING.md][contributing] and my PR is up to standards.
- [x] 🎨 The changes in this PR meet the design plan.
- [x] 🐛 I've tested my PR's source changes for any bugs/render issues.
- [x] 🧪 I've worked through build failures and tests are passing.
- [x] 📄 I've updated the necessary documentation changes.

#### Notes

[contributing]: https://github.com/web3community/DEV-NFT/blob/main/CONTRIBUTING.md

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -221,8 +220,8 @@ const home = ({ session }) => {
                   </div>
                 </div>
                 <div className="mt-6">
-                  <nav className="grid gap-y-8">
-                    {mobileMenu.map((item) => (
+                  <nav className="grid gap-y-6">
+                    {mobileMenu.map((item)=>(
```
Comment (AbhinavMV) [inline pages/index.js:224]: I have kept this mobileMenu array(with single item) it would be helpful if more elements needs to be added in future.
Let me know if this needs to be removed

Comment (mkubdev) [reply pages/index.js:224]: It's ok to keep the mobile menu. But we should clone the same as the normalMenu

**Review by mkubdev — APPROVED** [review]
LGTM 🚀

File: pages/index.js (hunk 1 above)
Comment (AbhinavMV) [reply pages/index.js:224]: Where would we use normalMenu? Currently there is no need for that.

**Review by krishguptadev — APPROVED** [review]

**Review by vinzvinci — APPROVED** [review]

File: pages/index.js (hunk 1 above)
Comment (krishguptadev) [inline pages/index.js:224]: Let's keep the spaces.

```suggestion
                    {mobileMenu.map((item) => (
```

Comment (shuklaritvik06) [reply pages/index.js:224]: +1

**Review by shuklaritvik06 — APPROVED** [review]

**Review by krishguptadev — APPROVED** [review]
